### ISSUE TITLE
the of Relu and batchNorm

### ISSUE THREAD

**Issue by mlx123** [delta-onera/delta_tb#1]
Hello.
I have some question about the relization of the Segnet.From the paper of the Segnet,it should be conv->BatchNorm->Relu.However,your relization of the Segnet  in segent.py is conv->Relu->BatchNorm .
![default](https://user-images.githubusercontent.com/28173246/50693704-a9a52780-1072-11e9-84d2-625c5e65c4dc.png)

![default](https://user-images.githubusercontent.com/28173246/50693799-01dc2980-1073-11e9-90c5-1ba2ee69cb7c.png)

thank you

**Comment by aboulch** [comment]
Hello,
You're right we didn't directly implemented the original SegNet, thanks for telling us.
I will make the modification in the next days and move the actual SegNet to SegNet_BN_Relu for differentiation.

**Comment by aboulch** [comment]
Hello,
I did the modification.
